// Generates supabase/seed.sql from the prototype's place data (seed-src/places.json) and the
// spreadsheet's opening hours. Run: node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { parseHours } from './lib-hours.mjs';

const places = JSON.parse(readFileSync('supabase/seed-src/places.json', 'utf8'));
const hours = JSON.parse(readFileSync('supabase/seed-src/hours.json', 'utf8'));
const q = (v) => (v == null ? 'null' : `'${String(v).replaceAll("'", "''")}'`);
const arr = (a) => `array[${a.map(q).join(',')}]::text[]`;
const json = (v) => `${q(JSON.stringify(v))}::jsonb`;

const out = ['-- GENERATED by scripts/gen-seed.mjs. Do not edit by hand.', 'begin;'];
places.forEach((p, i) => {
  out.push(`insert into public.places (id,name,short,area,lat,lng,category,vibe,about,moods,tags,budget_tier,price_label,hours_text,best_time,indoor,photos,food,dessert,insta,website,image_credit,sort_order) values (${[
    q(p.id), q(p.name), q(p.short), q(p.area), p.lat ?? 'null', p.lng ?? 'null', q(p.category ?? 'Spot'), q(p.vibe), q(p.about), arr(p.moods), arr(p.tags),
    p.budget, q(p.price), q(p.hours), q(p.best), p.indoor ? 'true' : 'false', arr(p.photos), json(p.food), json(p.dessert), q(p.insta || null), q(p.web || null), q(p.credit || null), i,
  ].join(',')}) on conflict (id) do update set name=excluded.name, short=excluded.short, vibe=excluded.vibe, about=excluded.about, moods=excluded.moods, tags=excluded.tags, photos=excluded.photos, food=excluded.food, dessert=excluded.dessert, updated_at=now();`);
  out.push(`insert into public.deals (place_id,title,code) values (${q(p.id)},${q(p.deal.title)},${q(p.deal.code)}) on conflict (code) do update set title=excluded.title;`);
  out.push(`insert into public.venues (place_id,name) values (${q(p.id)},${q(p.short)}) on conflict (place_id) do nothing;`);
  for (const h of parseHours(hours[p.id])) {
    out.push(`insert into public.place_hours (place_id,weekday,opens,closes,closes_next_day) values (${q(p.id)},${h.weekday},${q(h.opens)},${q(h.closes)},${h.closes_next_day}) on conflict do nothing;`);
  }
});

// What's on tonight / local picks (copied from the prototype, editable from the dashboard)
const EV = [['katara', '8:00 PM', 'Open-air cinema at the amphitheatre', 'Free', 'katara-3'], ['souq', '9:30 PM', 'Live oud in the courtyard', 'Free', 'souq-1'],
  ['lusail', '7:00 PM', 'Marina night market', 'QAR 20', 'lusail-2'], ['msheireb', 'Till 11 PM', 'Gallery late night', 'Free', 'msheireb-2'],
  ['pearl', '8:30 PM', 'Canal lights boat ride', 'QAR 40', 'pearl-3'], ['corniche', 'Sunset', 'Dhow sunset cruise', 'QAR 50', 'corniche-1']];
EV.forEach(([pl, t, name, tag, img], i) => out.push(`insert into public.events (place_id,title,time_text,tag,image,sort_order) values (${q(pl)},${q(name)},${q(t)},${q(tag)},${q(img)},${i});`));
const LO = [['@noor.eats', 'N', '#F5EEF6', 'souq', 'Skip the main alley. The luqaimat cart near the falcon souq is the real one.'],
  ['@doha.after.dark', 'D', '#3DF2FF', 'corniche', 'Park by the dhow harbour after 10. Karak, chapati, skyline. Whole night for 15 riyals.'],
  ['@hamad.walks', 'H', '#FFB23D', 'msheireb', 'Saffron ice cream, then ride the tram loop. Cheapest cute date in Doha.']];
LO.forEach(([h, ini, col, pl, quote], i) => out.push(`insert into public.local_picks (place_id,handle,initial,color,quote,sort_order) values (${q(pl)},${q(h)},${q(ini)},${q(col)},${q(quote)},${i});`));
out.push('commit;');
writeFileSync('supabase/seed.sql', out.join('\n') + '\n');
console.log('seed.sql:', places.length, 'places');
